# Site settings
title: From Marketer to Coder
header-img: img/home-bg.png
email: stevengalvis@ymail.com
copyright_name: stevengalvis
description: > # this means to ignore newlines until "baseurl:"
  It’s not a bug – it’s an undocumented feature.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stevengalvis
learn_profile: stevengalvis
email_username: stevengalvis@ymail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
